# Generated by Django 6.0.4 on 2026-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_hw', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
