# Generated by Django 6.0.4 on 2026-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_hw', '0005_product_artist_user_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='web_hw.tag'),
        ),
    ]
