services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-11-13-app
    env_file:
      - .env
    ports:
      - "82.114.226.145:8006:8000"
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    restart: unless-stopped
